### ISSUE TITLE
Change the way that rucio dataset is created

### ISSUE THREAD

**Issue by StevenCTimm** [DUNE/dune-justin#7]
Line 697-699 agents/justin-finder of the server side Justin code is creating a dataset at the beginning of the workflow with a finite lifetime.  The add_did call as called gives not only a rule of --lifetime-days but also put an expired_at: field on the dataset itself.

That field cannot be extended and when it expires, the dataset is deleted, as are any rules that reference it, with the --purge-replicas option to kill all the files that were in it as well.

Please modify the rucio call above  to create the dataset and then independently make a rule of the --lifetime-days.

**Comment by Andrew-McNab-UK** [comment]
No problem: I've deployed 00.13.07 with this changed and run a test workflow (1603) that caused usertests:output-test-02 to be created with a 3 day lifetime rule. There is now no expired_at on the dataset itself:

```
dunegpvm15.amcnab: rucio get-metadata usertests:output-test-02 | grep expired_at
expired_at:      None
```
